[HW-1-1] Домашнее задание 1. Задача 1.
securesvet/murzin_cpp pull request #1
Opened 2022-04-18 14:23 UTC by securesvet

Не знаю, надо ли делать мне всю домашку с первого сема, но пока просто делаю.

2022-06-08 08:25 UTC, ByKirilov requested changes

2022-06-08 08:25 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +    double A, B, C;
Однобуквенные переменные это плохо. Напиши нормальные названия

2022-06-08 08:25 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +    using namespace std;
Неймспейс лучше подключать не в функции

2022-06-08 08:25 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +    if (A!=0) {
Ставь пробелы между операторами и операндами. Сочетание клавиш `Ctrl+Alt+L` поможет приводить код впорядок. Перед ПРом всегда используй его

2022-06-08 08:25 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +        double D = (B * B - 4 * A * C);
Однобуквенные переменные это плохо. Напиши нормальные названия

2022-06-14 09:50 UTC, ByKirilov requested changes

2022-06-14 09:50 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +    double coefficientA, coefficientB, coefficientC;
Всё ещё не понятно, что за коэффициенты A, B, C. У них есть названия. Статья в википедии про квадратные уравнения в помощь

2022-06-14 09:50 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +                double rootX1 = (-coefficientB + discriminant) / (2 * coefficientA);
Во-первых, зачем тут X? Во-вторых использование цифр в именах переменных - так себе практика. Лучше назвать, например `firstRoot`

2022-06-14 09:50 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +                double rootX1 = -coefficientB / (2 * coefficientA);
Если он у тебя тут в принципе 1, зачем какая-то нумерация?

2022-06-14 09:50 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +        double rootX1 = -coefficientC / coefficientB;
Если он у тебя тут в принципе 1, зачем какая-то нумерация?

2022-06-14 09:50 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +            discriminant = sqrt(discriminant);
Почему бы сразу при вычислении дискриминанта не взять от него корень? Это на знак никак не повлияет

2022-06-14 09:50 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +         */
У комментария отступ съехал. Минор

2022-06-16 14:07 UTC, securesvet commented on HW-1-1/HW-1-1.cpp
> +            discriminant = sqrt(discriminant);
Дискриминант может быть отрицательным, а при взятии корня число под корнем должно быть неотрицательным, иначе будет ошибка

2022-06-18 06:06 UTC, ByKirilov commented on HW-1-1/HW-1-1.cpp
> +            discriminant = sqrt(discriminant);
Справедливо

2022-06-18 06:08 UTC, ByKirilov approved these changes

2022-06-20 18:53 UTC, merged