[CW-7-1] Вспомогательные функции
securesvet/murzin_cpp pull request #12
Opened 2022-05-27 10:53 UTC by securesvet

Ссылка на задачу: https://drive.google.com/drive/folders/1ig4-64jWag_5zS076cHkORNMV8dZIKyV

2022-06-08 09:37 UTC, ByKirilov requested changes

2022-06-08 09:37 UTC, ByKirilov commented on CW-7-1/CW-7-1.cpp
> +    //vec.reserve(sizeOfVector);
Что за закоментированные строки?

2022-06-08 09:37 UTC, ByKirilov commented on CW-7-1/CW-7-1.cpp
> +    std::vector<int> vec;
Сокращения зло

2022-06-08 09:37 UTC, ByKirilov commented on CW-7-1/CW-7-1.cpp
> +        int input_num;
Мы используем camelCase. Каждое слово начинается с большой буквы

2022-06-08 09:37 UTC, ByKirilov commented on CW-7-1/CW-7-1.cpp
> +} // Функция  для ввода vector<int>
Этот комментарий к чему относится?

2022-06-08 09:37 UTC, ByKirilov commented on CW-7-1/CW-7-1.cpp
> +std::vector<int> vectorStoi(std::vector<std::string> vec) {
Что с названием? Давай понятнее

2022-06-08 09:37 UTC, ByKirilov commented on CW-7-1/CW-7-1.cpp
> +    std::vector<int> vecInt;
Сокращения зло

2022-06-08 09:37 UTC, ByKirilov commented on CW-7-1/CW-7-1.cpp
> +std::vector<std::string> vectorItos(std::vector<int> inputVector) {
Хочу понятное название

2022-06-08 09:37 UTC, ByKirilov commented on CW-7-1/CW-7-1.cpp
> +
Зачем этот отступ?

2022-06-12 15:10 UTC, securesvet commented on CW-7-1/CW-7-1.cpp
> +std::vector<int> vectorStoi(std::vector<std::string> vec) {
Типо string to integer, но лан, так и напишу

2022-06-14 10:34 UTC, ByKirilov approved these changes

2022-06-14 10:34 UTC, ByKirilov commented on CW-7-1/CW-7-1.cpp
> +// Функция для вывода вектора
Этот комментарий над объявлением шаблона написать бы. Минор

2022-06-16 13:44 UTC, merged